name: share_dream
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  oktoast: ^3.0.0
  #网络请求
  dio: ^4.0.0
  rxdart: ^0.26.0
  common_utils: ^2.0.2
  #flustars: ^2.0.1
  sp_util: ^2.0.3
  flutter_swiper: ^1.1.6
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  sticky_headers: ^0.2.0
  #路由
  fluro: ^2.0.3
  azlistview: ^1.1.1
  keyboard_actions: ^3.4.0
  webview_flutter: ^2.0.4
  flutter_slidable: ^0.6.0
  cached_network_image: ^3.0.0
  sprintf: ^6.0.0
  provider: ^5.0.0
  barcode_scan: ^3.0.1
#  flutter_2d_amap:
#    git:
#      ref: 323fcf8
#      url: https://github.com/simplezhli/flutter_2d_amap.git
  #国际化
  intl: ^0.17.0
  device_info: ^2.0.0
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  flow_builder: ^0.0.2
  meta: ^1.3.0
  very_good_analysis: ^2.0.0
  #本地存储
  shared_preferences: ^2.0.5
  #首屏
  flutter_native_splash: ^1.1.8+4
  flare_splash_screen: ^4.0.0
  http_certificate_pinning: ^2.0.0
  ##定时器
  timer_count_down: ^2.0.1
  #手机像素适配
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  intl_translation: ^0.17.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: assets/images/startPage/default.jpeg # 对应生成iOS中LaunchImage图片，包含1x2x3x
  color: "#ffffff" # 闪屏页背景色
  fill: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets-generator-begin
    # assets/images/*
    # assets/images/startPage/*
    - assets/images/startPage/default.jpeg
    # assets/images/guidePage/*
    - assets/images/guidePage/guide_3.webp
    - assets/images/guidePage/guide_2.webp
    - assets/images/guidePage/guide_1.webp
    # assets-generator-end
    - assets/crt/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
